### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by OrdinaryOrgan** [JingShing/NovelAI-4chan-lowvram-ver#2]
I'm happy to see a version of novelai that could run on my laptop, thank you for your effort! But I still face a problem that after I run the start.bat and wait, there is just nothing happens, without opening a certain website.
I've checked the main.py and install fastapi and uvicorn already, could you tell me why it doesn't work?
![image](https://user-images.githubusercontent.com/68810477/196453272-79898cee-73ed-4ed5-96e8-122285a3face.png)

**Comment by JingShing** [comment]
It has done already after 0,0,0,0:6969 showed. You need to open it at your local url : http://127.0.0.1:6969/

**Comment by OrdinaryOrgan** [comment]
OK, I've already solved this problem! Thanks a lot!
